File recipes
ALEXDRUGS/ListRecipes pull request #2
Opened 2022-12-31 10:15 UTC by ALEXDRUGS

2023-01-01 01:43 UTC, iStemmer commented on src/main/java/com/app/recipe/Controllers/RecipeController.java
> +    @Operation(description = "Recipe don't has been added")
не совсем совпадает описание (здесь можно написать что-то вроде ) 
"Adds new one to map of recipes"

2023-01-01 01:43 UTC, iStemmer commented on src/main/java/com/app/recipe/Controllers/RecipeController.java
пустая строка не нужна

2023-01-01 01:44 UTC, iStemmer commented on src/main/java/com/app/recipe/service/RecipeService.java
пустая строка

2023-01-05 17:38 UTC, iStemmer commented on src/main/java/com/app/recipe/Controllers/IngredientController.java
> +    private final IngredientServiceImpl ingredientServiceImpl;
тут было правильно, инжектить надо интерфейс

2023-01-05 17:39 UTC, iStemmer commented on src/main/java/com/app/recipe/Controllers/FileController.java
> +    private final FileServiceImpl fileServiceImpl;
инжектить надо интерфейс

2023-01-05 17:39 UTC, iStemmer commented on src/main/java/com/app/recipe/Controllers/RecipeController.java
> +    private final RecipeServiceImpl recipeServiceImpl;
тут было правильно, инжектить надо интерфейс

2023-01-05 17:40 UTC, iStemmer commented on src/main/java/com/app/recipe/service/impl/IngredientServiceImpl.java
> +    private final FileServiceImpl fileServiceImpl;
инжектить надо интерфейс

2023-01-05 17:40 UTC, iStemmer commented on src/main/java/com/app/recipe/service/impl/RecipeServiceImpl.java
> +    private final FileServiceImpl fileServiceImpl;
тут было правильно, инжектить надо интерфейс

2023-01-05 17:41 UTC, iStemmer commented on src/main/java/com/app/recipe/service/impl/FileServiceImpl.java
> +            throw new RuntimeException();
надо бросать свои ошибки

2023-01-05 17:42 UTC, iStemmer commented on src/main/java/com/app/recipe/service/impl/FileServiceImpl.java
> +            throw new RuntimeException();
надо бросать свои ошибки

2023-01-08 18:52 UTC, OlgaLugacheva requested changes

2023-01-08 18:52 UTC, OlgaLugacheva commented on src/main/java/com/app/recipe/Controllers/FileController.java
> +package com.app.recipe.controllers;
здесь пакет controllers а в дереве проекта Controllers

2023-01-08 18:52 UTC, OlgaLugacheva commented on src/main/java/com/app/recipe/service/impl/FileServiceImpl.java
> +            return Files.createFile(Path.of(recipeFilePath, suffix));
сначала нужно проверить, что такой файл не существует, прежде чем его создавать
Files.exists

2023-01-08 22:05 UTC, ALEXDRUGS commented on src/main/java/com/app/recipe/Controllers/FileController.java
> +package com.app.recipe.controllers;
покажите где у меня в дереве Controllers я вижу controllers

2023-01-08 22:54 UTC, ALEXDRUGS commented on src/main/java/com/app/recipe/service/impl/FileServiceImpl.java
> +            return Files.createFile(Path.of(recipeFilePath, suffix));
делал в точности как у Зураба как учите так и делаю

2023-01-09 06:33 UTC, OlgaLugacheva commented on src/main/java/com/app/recipe/Controllers/FileController.java
> +package com.app.recipe.controllers;
![image](https://user-images.githubusercontent.com/12631461/211252011-2ef8eacc-598c-4695-94f6-6782ad371291.png)

2023-01-09 18:06 UTC, OlgaLugacheva requested changes

2023-01-09 18:06 UTC, OlgaLugacheva commented on src/main/java/com/app/recipe/service/impl/FileServiceImpl.java
> +        return null;
return Path.of(recipeFilePath, suffix);

2023-01-10 08:52 UTC, merged